apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-monitor
  namespace: monitoring
  labels:
    release: monitoring   # 🔥 REQUIRED
spec:
  selector:
    matchLabels:
      app: gateway
  namespaceSelector:
    matchNames:
      - serving
  endpoints:
    - port: http
      path: /metrics
      interval: 10s