apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: serving
type: Opaque
stringData:
  PG_DSN: postgresql://postgres:postgres@postgres-postgresql.data.svc.cluster.local:5432/visiondb
  MINIO_ACCESS: minio
  MINIO_SECRET: minio123456